### ISSUE TITLE
Update to release Bootstrap code?

### ISSUE THREAD

**Issue by resistorsoftware** [ablesense/bootstrap-polaris#1]
Just curious if you're going to jump from Beta 2 to the January 18th official release version Bootstrap?

**Comment by derekmorash** [comment]
No plans yet for making the switch. I'm not sure if it's really worth it since most bootstrap components are being removed or replaced with the polaris equivalent. Everything we've built so far has been tested across a large number of browsers and has been designed to fail gracefully in older browsers that don't support newer features.

There's still some work to be done here to be more or less 1 to 1 with polaris but we've been using this for months in our own apps without any problem.

Thanks for the interest!
